// This is a single-line comment

/* 
This is a multi-line comment.
It spans multiple lines.
*/

pipeline {
    agent any
//  agent {label 'slave-1'}

    tools {
        maven "maven3"
        jdk "jdk17"
    }

    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'ibtisam', url: 'https://github.com/ibtisamops/0.1.1_Boardgame.git'
//              git branch: "${params.Branch_name}", url: 'https://github.com/ibtisamops/0.1.1_Boardgame.git'
            }
        }

        stage('Compile') {
            steps {
                sh 'mvn compile'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Package') {
            steps {
                sh 'mvn package'
            }
        }
        stage('Install') {
            steps {
                sh 'mvn install'
            }
        }
    }
}

